[tool.poetry]
name = "flowforge"
version = "0.1.0"
description = "Workflow automation tool with integrations and AI assistance"
authors = ["Your Name <your.email@example.com>"]
license = "MIT"
readme = "README.md"
packages = [
    { include = "flowforge" }
]

[tool.poetry.dependencies]
python = "^3.8"
pyyaml = "^6.0"
click = "^8.1.3"
requests = "^2.28.1"
numpy = "^1.23.0"
fastapi = "^0.95.0"
uvicorn = "^0.21.1"
python-dotenv = "^1.0.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"
black = "^23.3.0"
isort = "^5.12.0"
mypy = "^1.3.0"

[tool.poetry.scripts]
flowforge = "flowforge.apps.cli.__main__:cli"
flowforge-server = "flowforge.apps.server.api:app"
flowforge-worker = "flowforge.apps.worker.runner:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ["py38"]

[tool.isort]
profile = "black"
line_length = 88